import 'package:flutter/material.dart';

// --- MODELS ---

class Article {
  final String id;
  final String title;
  final String category;
  final String imageUrl;
  final String content;

  Article({
    required this.id,
    required this.title,
    required this.category,
    required this.imageUrl,
    required this.content,
  });
}

class VideoItem {
  final String id;
  final String title;
  final String duration;
  final String thumbnailUrl; // Link ảnh bìa
  final String videoUrl;     // Link video Youtube chuẩn (MỚI THÊM)
  final String author;

  VideoItem({
    required this.id,
    required this.title,
    required this.duration,
    required this.thumbnailUrl,
    required this.videoUrl,
    required this.author,
  });
}

class Medicine {
  final String id;
  final String name;
  final String usage;
  final String dosage;
  final String warning;

  Medicine({
    required this.id,
    required this.name,
    required this.usage,
    required this.dosage,
    required this.warning,
  });
}

// --- MOCK DATA (Dữ liệu mẫu) ---

final List<Article> sampleArticles = [
  Article(
    id: '1',
    title: '5 Thói quen giúp tim mạch khỏe mạnh',
    category: 'Sức khỏe',
    imageUrl: 'https://images.unsplash.com/photo-1628348068343-c6a848d2b6dd?auto=format&fit=crop&q=80&w=500',
    content: '1. Đi bộ mỗi ngày...\n2. Ăn nhạt...\n3. Giữ tinh thần lạc quan...',
  ),
  Article(
    id: '2',
    title: 'Thực đơn tốt cho người tiểu đường',
    category: 'Dinh dưỡng',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=500',
    content: 'Người tiểu đường nên ăn nhiều rau xanh, hạn chế tinh bột trắng...',
  ),
  Article(
    id: '3',
    title: 'Bài tập dưỡng sinh buổi sáng',
    category: 'Vận động',
    imageUrl: 'https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&q=80&w=500',
    content: 'Hít thở sâu, vươn vai nhẹ nhàng giúp khí huyết lưu thông...',
  ),
];

final List<Medicine> sampleMedicines = [
  Medicine(
    id: 'm1',
    name: 'Panadol (Paracetamol)',
    usage: 'Giảm đau, hạ sốt nhẹ đến trung bình. Dùng khi đau đầu, sốt, đau răng, đau cơ.',
    dosage: '500-1000mg/lần (1-2 viên), cách nhau 4-6 giờ. Tối đa 4g/ngày.',
    warning: 'Không uống rượu bia khi dùng thuốc. Không dùng quá liều gây độc gan. Người bệnh gan cần thận trọng.',
  ),
  Medicine(
    id: 'm2',
    name: 'Hoạt huyết dưỡng não',
    usage: 'Tăng cường tuần hoàn máu não, giảm đau đầu, chóng mặt, ù tai, cải thiện trí nhớ.',
    dosage: '2 viên/lần, ngày 2-3 lần sau ăn.',
    warning: 'Phụ nữ có thai, người rối loạn đông máu cần hỏi ý kiến bác sĩ trước khi dùng.',
  ),
  Medicine(
    id: 'm3',
    name: 'Berberin (Tiêu hóa)',
    usage: 'Điều trị tiêu chảy, đau bụng do nhiễm khuẩn đường ruột.',
    dosage: '300-500mg/lần (4-6 viên), ngày 2-3 lần trước ăn.',
    warning: 'Tránh dùng cho phụ nữ có thai, cho con bú. Có thể gây táo bón nếu dùng kéo dài.',
  ),
  Medicine(
    id: 'm4',
    name: 'Aspirin (Axit Acetylsalicylic)',
    usage: 'Giảm đau, hạ sốt, chống viêm. Liều thấp phòng ngừa đột quỵ, nhồi máu cơ tim.',
    dosage: 'Giảm đau: 300-500mg/lần. Phòng tim mạch: 75-100mg/ngày.',
    warning: 'Không dùng cho người loét dạ dày, rối loạn đông máu. Uống sau ăn. Có thể gây xuất huyết tiêu hóa.',
  ),
  Medicine(
    id: 'm5',
    name: 'Amlodipine (Hạ huyết áp)',
    usage: 'Điều trị tăng huyết áp mạn tính, đau thắt ngực do thiếu máu cơ tim.',
    dosage: '5-10mg/ngày, uống 1 lần vào buổi sáng.',
    warning: 'Có thể gây chóng mặt, phù chân. Không tự ý ngừng thuốc đột ngột. Theo dõi huyết áp thường xuyên.',
  ),
  Medicine(
    id: 'm6',
    name: 'Metformin (Điều trị tiểu đường)',
    usage: 'Điều trị tiểu đường type 2, giúp kiểm soát đường huyết.',
    dosage: '500-850mg/lần, ngày 2-3 lần trong hoặc sau bữa ăn. Tăng dần liều theo chỉ định.',
    warning: 'Có thể gây buồn nôn, đầy hơi. Không dùng cho người suy thận nặng. Theo dõi chức năng thận định kỳ.',
  ),
  Medicine(
    id: 'm7',
    name: 'Simvastatin (Hạ mỡ máu)',
    usage: 'Giảm cholesterol máu, phòng ngừa bệnh tim mạch.',
    dosage: '10-40mg/ngày, uống 1 lần vào buổi tối.',
    warning: 'Có thể gây đau cơ, tăng men gan. Tránh ăn bưởi khi dùng thuốc. Kiểm tra gan định kỳ.',
  ),
  Medicine(
    id: 'm8',
    name: 'Omeprazole (Bảo vệ dạ dày)',
    usage: 'Điều trị loét dạ dày, trào ngược dạ dày thực quản, giảm tiết acid.',
    dosage: '20mg/ngày, uống vào buổi sáng trước ăn 30 phút.',
    warning: 'Dùng lâu dài có thể giảm hấp thu vitamin B12, calcium. Không nhai, nghiền viên nang.',
  ),
  Medicine(
    id: 'm9',
    name: 'Cetirizine (Chống dị ứng)',
    usage: 'Điều trị viêm mũi dị ứng, mày đay, ngứa da.',
    dosage: '10mg/ngày, uống 1 lần vào buổi tối.',
    warning: 'Có thể gây buồn ngủ. Không lái xe hoặc vận hành máy móc sau khi uống. Tránh uống rượu.',
  ),
  Medicine(
    id: 'm10',
    name: 'Glucosamine Sulfate (Xương khớp)',
    usage: 'Hỗ trợ điều trị thoái hóa khớp, giảm đau nhức xương khớp.',
    dosage: '1500mg/ngày, chia 1-3 lần sau ăn.',
    warning: 'Người dị ứng hải sản cần thận trọng. Hiệu quả sau 4-8 tuần dùng liên tục.',
  ),
  Medicine(
    id: 'm11',
    name: 'Vitamin D3 + Calcium',
    usage: 'Bổ sung canxi và vitamin D, phòng ngừa loãng xương ở người cao tuổi.',
    dosage: '1-2 viên/ngày sau bữa ăn.',
    warning: 'Uống nhiều nước. Không dùng quá liều gây sỏi thận. Phơi nắng buổi sáng để tăng hiệu quả.',
  ),
  Medicine(
    id: 'm12',
    name: 'Bisoprolol (Thuốc tim)',
    usage: 'Điều trị tăng huyết áp, suy tim mạn, rối loạn nhịp tim.',
    dosage: '2.5-10mg/ngày, uống 1 lần vào buổi sáng.',
    warning: 'Không tự ý ngừng thuốc đột ngột. Có thể gây chậm nhịp tim. Theo dõi nhịp tim, huyết áp thường xuyên.',
  ),
  Medicine(
    id: 'm13',
    name: 'Ginkgo Biloba (Bổ não)',
    usage: 'Cải thiện tuần hoàn máu não, tăng cường trí nhớ, giảm ù tai, chóng mặt.',
    dosage: '40mg/lần, ngày 3 lần sau ăn hoặc 120mg/ngày.',
    warning: 'Có thể tương tác với thuốc chống đông máu. Hỏi bác sĩ nếu đang dùng aspirin hoặc warfarin.',
  ),
  Medicine(
    id: 'm14',
    name: 'Allopurinol (Điều trị Gout)',
    usage: 'Giảm acid uric trong máu, phòng ngừa cơn gout tái phát.',
    dosage: '100-300mg/ngày, uống sau ăn.',
    warning: 'Uống nhiều nước (2-3 lít/ngày). Có thể gây phát ban da. Không dùng trong cơn gout cấp.',
  ),
  Medicine(
    id: 'm15',
    name: 'Enalapril (Thuốc tim mạch)',
    usage: 'Điều trị tăng huyết áp, suy tim, bảo vệ thận ở người tiểu đường.',
    dosage: '5-20mg/ngày, chia 1-2 lần.',
    warning: 'Có thể gây ho khan, chóng mặt khi đứng dậy nhanh. Theo dõi chức năng thận, kali máu.',
  ),
  Medicine(
    id: 'm16',
    name: 'Levothyroxine (Hormone tuyến giáp)',
    usage: 'Điều trị suy giáp, bù trừ hormone thyroxine.',
    dosage: 'Theo chỉ định bác sĩ, thường 50-200mcg/ngày uống sáng sớm lúc đói.',
    warning: 'Cách các loại thuốc, thực phẩm khác ít nhất 30 phút. Kiểm tra tuyến giáp định kỳ.',
  ),
  Medicine(
    id: 'm17',
    name: 'Prednisone (Corticosteroid)',
    usage: 'Chống viêm, điều trị các bệnh tự miễn, dị ứng nặng, hen suyễn.',
    dosage: 'Theo chỉ định bác sĩ, thường 5-60mg/ngày.',
    warning: 'Không tự ý dừng thuốc đột ngột. Dùng lâu dài gây loãng xương, tăng đường huyết, giảm miễn dịch.',
  ),
  Medicine(
    id: 'm18',
    name: 'Clopidogrel (Chống đông máu)',
    usage: 'Phòng ngừa đột quỵ, nhồi máu cơ tim sau can thiệp mạch vành.',
    dosage: '75mg/ngày, uống 1 lần.',
    warning: 'Có thể gây chảy máu, bầm tím dễ dàng. Báo bác sĩ trước khi phẫu thuật. Không dùng chung với NSAID.',
  ),
  Medicine(
    id: 'm19',
    name: 'Furosemide (Lợi tiểu)',
    usage: 'Điều trị phù phổi, phù ngoại biên, tăng huyết áp kháng trị.',
    dosage: '20-80mg/ngày, uống vào buổi sáng.',
    warning: 'Có thể gây mất kali, chóng mặt. Bổ sung kali qua thức ăn. Theo dõi điện giải đồ.',
  ),
  Medicine(
    id: 'm20',
    name: 'Melatonin (Hỗ trợ ngủ)',
    usage: 'Cải thiện giấc ngủ, điều trị mất ngủ ở người cao tuổi.',
    dosage: '1-5mg, uống trước khi ngủ 30-60 phút.',
    warning: 'Có thể gây buồn ngủ ban ngày nếu dùng quá liều. Tránh lái xe sau khi uống.',
  ),
  Medicine(
    id: 'm21',
    name: 'Tamsulosin (Phì đại tuyến tiền liệt)',
    usage: 'Điều trị phì đại lành tính tuyến tiền liệt, cải thiện tiểu tiện.',
    dosage: '0.4mg/ngày, uống sau bữa ăn cùng giờ mỗi ngày.',
    warning: 'Có thể gây chóng mặt, hạ huyết áp tư thế. Đứng dậy từ từ. Không nhai, nghiền viên thuốc.',
  ),
  Medicine(
    id: 'm22',
    name: 'Ranitidine/Famotidine (Giảm acid)',
    usage: 'Điều trị loét dạ dày, trào ngược, giảm tiết acid dạ dày.',
    dosage: '150mg x 2 lần/ngày hoặc 300mg trước khi ngủ.',
    warning: 'Tránh các thực phẩm cay, cà phê, rượu. Uống sau ăn 1 giờ hoặc trước khi ngủ.',
  ),
  Medicine(
    id: 'm23',
    name: 'Diazepam (Thuốc an thần)',
    usage: 'Điều trị lo âu, rối loạn giấc ngủ, co thắt cơ.',
    dosage: '2-10mg/lần, ngày 2-3 lần theo chỉ định.',
    warning: 'Gây nghiện nếu dùng lâu dài. Không uống rượu. Có thể gây buồn ngủ, giảm phản xạ. Không lái xe.',
  ),
  Medicine(
    id: 'm24',
    name: 'Lactulose (Nhuận tràng)',
    usage: 'Điều trị táo bón mạn tính, làm mềm phân.',
    dosage: '15-30ml/lần, ngày 1-2 lần.',
    warning: 'Có thể gây đầy hơi, tiêu chảy nếu dùng quá liều. Uống nhiều nước. Hiệu quả sau 24-48 giờ.',
  ),
  Medicine(
    id: 'm25',
    name: 'Atorvastatin (Hạ mỡ máu)',
    usage: 'Giảm cholesterol, triglycerid, phòng ngừa bệnh tim mạch.',
    dosage: '10-80mg/ngày, uống vào buổi tối.',
    warning: 'Có thể gây đau cơ, tăng men gan. Tránh ăn bưởi. Kiểm tra chức năng gan định kỳ.',
  ),
  Medicine(
    id: 'm26',
    name: 'Insulin (Tiêm tiểu đường)',
    usage: 'Điều trị tiểu đường type 1 và type 2 không kiểm soát được bằng thuốc uống.',
    dosage: 'Theo chỉ định bác sĩ, tiêm dưới da trước bữa ăn.',
    warning: 'Có thể gây hạ đường huyết. Luôn mang đồ ăn nhẹ. Kiểm tra đường huyết thường xuyên. Bảo quản lạnh.',
  ),
  Medicine(
    id: 'm27',
    name: 'Warfarin (Chống đông máu)',
    usage: 'Phòng ngừa huyết khối, đột quỵ ở người rung nhĩ, van tim nhân tạo.',
    dosage: 'Liều cá thể hóa theo INR, thường 2-10mg/ngày.',
    warning: 'Cần xét nghiệm INR định kỳ. Tránh rau xanh đậm, gan động vật. Báo bác sĩ trước phẫu thuật.',
  ),
  Medicine(
    id: 'm28',
    name: 'Tramadol (Giảm đau mạnh)',
    usage: 'Điều trị đau vừa đến nặng, đau mạn tính.',
    dosage: '50-100mg/lần, cách 4-6 giờ, tối đa 400mg/ngày.',
    warning: 'Có thể gây buồn nôn, chóng mặt, táo bón. Nguy cơ nghiện nếu dùng lâu dài. Không uống rượu.',
  ),
  Medicine(
    id: 'm29',
    name: 'Donepezil (Alzheimer)',
    usage: 'Điều trị bệnh Alzheimer nhẹ đến trung bình, cải thiện trí nhớ.',
    dosage: '5-10mg/ngày, uống vào buổi tối trước khi ngủ.',
    warning: 'Có thể gây buồn nôn, tiêu chảy, mất ngủ. Hiệu quả chậm, cần dùng đều. Không tự ý ngừng thuốc.',
  ),
  Medicine(
    id: 'm30',
    name: 'Salbutamol (Xịt hen phế quản)',
    usage: 'Giãn phế quản, điều trị hen suyễn, COPD.',
    dosage: '1-2 nhát xịt khi khó thở, cách 4-6 giờ.',
    warning: 'Có thể gây run tay, tim đập nhanh. Súc miệng sau khi xịt. Không dùng quá liều.',
  ),
  Medicine(
    id: 'm31',
    name: 'Vitamin B Complex',
    usage: 'Bổ sung vitamin nhóm B, cải thiện thần kinh, giảm mệt mỏi.',
    dosage: '1 viên/ngày sau bữa ăn sáng.',
    warning: 'Có thể làm nước tiểu có màu vàng đậm (bình thường). Không cần uống nếu chế độ ăn đầy đủ.',
  ),
  Medicine(
    id: 'm32',
    name: 'Ibuprofen (Giảm đau, hạ sốt)',
    usage: 'Giảm đau, hạ sốt, chống viêm. Dùng cho đau khớp, đau đầu, đau răng.',
    dosage: '200-400mg/lần, ngày 3-4 lần sau ăn. Tối đa 1200mg/ngày.',
    warning: 'Có thể gây loét dạ dày. Uống sau ăn. Không dùng cho người loét, suy thận. Tránh dùng lâu dài.',
  ),
  Medicine(
    id: 'm33',
    name: 'Spironolactone (Lợi tiểu giữ kali)',
    usage: 'Điều trị suy tim, tăng huyết áp, phù do gan, thận.',
    dosage: '25-100mg/ngày.',
    warning: 'Có thể gây tăng kali máu. Tránh ăn nhiều chuối, cam. Theo dõi kali máu định kỳ.',
  ),
  Medicine(
    id: 'm34',
    name: 'Colchicine (Điều trị cơn Gout cấp)',
    usage: 'Điều trị cơn gout cấp, giảm viêm khớp.',
    dosage: '0.5mg mỗi giờ cho đến khi hết đau hoặc tối đa 6mg/cơn.',
    warning: 'Có thể gây tiêu chảy nặng, buồn nôn. Ngừng ngay khi có tiêu chảy. Không dùng cho người suy thận nặng.',
  ),
  Medicine(
    id: 'm35',
    name: 'Pregabalin (Đau thần kinh)',
    usage: 'Điều trị đau thần kinh, đau dây thần kinh tọa, đau do tiểu đường.',
    dosage: '75-300mg/ngày, chia 2-3 lần.',
    warning: 'Có thể gây buồn ngủ, chóng mặt. Không lái xe. Tăng giảm liều từ từ. Nguy cơ nghiện.',
  ),
  Medicine(
    id: 'm36',
    name: 'Gabapentin (Đau thần kinh)',
    usage: 'Điều trị đau thần kinh sau herpes zoster, động kinh, đau mạn tính.',
    dosage: '300-900mg/lần, ngày 3 lần. Tăng dần từ liều thấp.',
    warning: 'Có thể gây buồn ngủ, chóng mặt, phù ngoại biên. Không ngừng thuốc đột ngột.',
  ),
  Medicine(
    id: 'm37',
    name: 'Losartan (Hạ huyết áp)',
    usage: 'Điều trị tăng huyết áp, bảo vệ thận ở người tiểu đường, suy tim.',
    dosage: '25-100mg/ngày, uống 1 lần.',
    warning: 'Có thể gây chóng mặt, tăng kali máu. Không dùng cho phụ nữ có thai. Theo dõi chức năng thận.',
  ),
  Medicine(
    id: 'm38',
    name: 'Hydrochlorothiazide (Lợi tiểu)',
    usage: 'Điều trị tăng huyết áp, phù do suy tim, thận.',
    dosage: '12.5-25mg/ngày, uống buổi sáng.',
    warning: 'Có thể gây mất kali, tăng đường huyết. Phơi nắng dễ cháy da. Bổ sung kali qua thức ăn.',
  ),
  Medicine(
    id: 'm39',
    name: 'Levothyroxine (Hormone tuyến giáp)',
    usage: 'Điều trị suy giáp, bổ sung hormone thyroid.',
    dosage: '50-200mcg/ngày, uống sáng sớm lúc đói.',
    warning: 'Cách thuốc khác và thức ăn 30-60 phút. Kiểm tra TSH định kỳ. Không tự ý thay đổi liều.',
  ),
  Medicine(
    id: 'm40',
    name: 'Alprazolam (An thần)',
    usage: 'Điều trị lo âu, rối loạn hoảng sợ, mất ngủ ngắn hạn.',
    dosage: '0.25-0.5mg/lần, ngày 2-3 lần.',
    warning: 'Gây nghiện nhanh. Chỉ dùng ngắn hạn. Không uống rượu. Có thể gây buồn ngủ, lú lẫn.',
  ),
  Medicine(
    id: 'm41',
    name: 'Zolpidem (Thuốc ngủ)',
    usage: 'Điều trị mất ngủ, giúp dễ ngủ hơn.',
    dosage: '5-10mg trước khi ngủ. Chỉ dùng khi có thể ngủ đủ 7-8 giờ.',
    warning: 'Có thể gây mơ màng, đi lại vô thức khi ngủ. Gây nghiện nếu dùng lâu. Không lái xe sau khi uống.',
  ),
  Medicine(
    id: 'm42',
    name: 'Pantoprazole (Bảo vệ dạ dày)',
    usage: 'Điều trị loét dạ dày, trào ngược, hội chứng Zollinger-Ellison.',
    dosage: '40mg/ngày, uống buổi sáng trước ăn 30 phút.',
    warning: 'Dùng lâu dài có thể giảm hấp thu vitamin B12, magnesium. Không nhai viên thuốc.',
  ),
  Medicine(
    id: 'm43',
    name: 'Esomeprazole (Giảm acid dạ dày)',
    usage: 'Điều trị trào ngược dạ dày thực quản, loét tiêu hóa.',
    dosage: '20-40mg/ngày, uống buổi sáng.',
    warning: 'Có thể gây đau đầu, tiêu chảy. Dùng lâu dài tăng nguy cơ gãy xương. Uống nuốt nguyên viên.',
  ),
  Medicine(
    id: 'm44',
    name: 'Loratadine (Chống dị ứng)',
    usage: 'Điều trị viêm mũi dị ứng, mày đay, ngứa da không rõ nguyên nhân.',
    dosage: '10mg/ngày, uống 1 lần.',
    warning: 'Ít gây buồn ngủ hơn thuốc dị ứng cũ. An toàn cho người lái xe. Có thể gây khô miệng.',
  ),
  Medicine(
    id: 'm45',
    name: 'Montelukast (Hen suyễn)',
    usage: 'Phòng ngừa hen suyễn, viêm mũi dị ứng theo mùa.',
    dosage: '10mg/ngày, uống vào buổi tối.',
    warning: 'Không dùng cho cơn hen cấp. Có thể gây thay đổi tâm trạng, ác mộng. Báo bác sĩ nếu có triệu chứng tâm thần.',
  ),
  Medicine(
    id: 'm46',
    name: 'Prednisone (Corticosteroid)',
    usage: 'Chống viêm mạnh, điều trị hen, COPD, viêm khớp, bệnh tự miễn.',
    dosage: '5-60mg/ngày tùy bệnh, chia 1-2 lần.',
    warning: 'Dùng lâu gây loãng xương, tăng đường huyết, giảm miễn dịch. Không ngừng đột ngột. Uống với thức ăn.',
  ),
  Medicine(
    id: 'm47',
    name: 'Methylprednisolone (Corticosteroid)',
    usage: 'Chống viêm, điều trị dị ứng nặng, viêm khớp, lupus.',
    dosage: '4-48mg/ngày tùy bệnh.',
    warning: 'Tác dụng phụ giống Prednisone. Cần giảm liều từ từ. Theo dõi đường huyết, huyết áp.',
  ),
  Medicine(
    id: 'm48',
    name: 'Dexamethasone (Corticosteroid)',
    usage: 'Chống viêm, chống phù não, điều trị dị ứng, hen nặng.',
    dosage: '0.5-10mg/ngày tùy bệnh.',
    warning: 'Corticosteroid mạnh nhất. Tác dụng phụ nặng nếu dùng lâu. Chỉ dùng theo chỉ định chặt chẽ.',
  ),
  Medicine(
    id: 'm49',
    name: 'Ciprofloxacin (Kháng sinh)',
    usage: 'Điều trị nhiễm khuẩn đường tiết niệu, đường ruột, hô hấp.',
    dosage: '500-750mg/lần, ngày 2 lần.',
    warning: 'Có thể gây đứt gân, đặc biệt gân Achilles. Tránh ánh nắng mặt trời. Uống nhiều nước. Tránh sữa, canxi khi uống thuốc.',
  ),
  Medicine(
    id: 'm50',
    name: 'Amoxicillin (Kháng sinh)',
    usage: 'Điều trị nhiễm khuẩn đường hô hấp, tai, họng, da.',
    dosage: '500mg/lần, ngày 3 lần hoặc 875mg, ngày 2 lần.',
    warning: 'Có thể gây dị ứng (phát ban, sưng). Người dị ứng penicillin không được dùng. Uống đủ liều trình.',
  ),
  Medicine(
    id: 'm51',
    name: 'Azithromycin (Kháng sinh)',
    usage: 'Điều trị nhiễm khuẩn đường hô hấp, da, lây qua đường tình dục.',
    dosage: '500mg ngày đầu, sau đó 250mg/ngày trong 4 ngày.',
    warning: 'Có thể gây rối loạn nhịp tim. Người bệnh tim cần thận trọng. Có thể gây tiêu chảy.',
  ),
  Medicine(
    id: 'm52',
    name: 'Levofloxacin (Kháng sinh)',
    usage: 'Điều trị viêm phổi, nhiễm khuẩn đường tiết niệu, viêm xoang.',
    dosage: '250-750mg/ngày tùy nhiễm trùng.',
    warning: 'Nhóm fluoroquinolone, có nguy cơ đứt gân. Có thể gây rối loạn đường huyết. Tránh ánh nắng.',
  ),
  Medicine(
    id: 'm53',
    name: 'Doxycycline (Kháng sinh)',
    usage: 'Điều trị nhiễm khuẩn hô hấp, da, mụn trứng cá, sốt rét.',
    dosage: '100mg/lần, ngày 2 lần.',
    warning: 'Tăng nhạy cảm ánh sáng. Không dùng cho trẻ em, phụ nữ có thai. Có thể gây buồn nôn.',
  ),
  Medicine(
    id: 'm54',
    name: 'Cephalexin (Kháng sinh)',
    usage: 'Điều trị nhiễm khuẩn da, đường hô hấp, xương khớp.',
    dosage: '500mg/lần, ngày 3-4 lần.',
    warning: 'Người dị ứng penicillin có thể dị ứng chéo. Có thể gây tiêu chảy. Uống đủ liều trình.',
  ),
  Medicine(
    id: 'm55',
    name: 'Nitrofurantoin (Kháng sinh)',
    usage: 'Điều trị và phòng ngừa nhiễm trùng đường tiết niệu.',
    dosage: '50-100mg/lần, ngày 4 lần hoặc 100mg, ngày 2 lần.',
    warning: 'Uống với thức ăn. Có thể làm nước tiểu màu nâu. Không dùng cho người suy thận.',
  ),
  Medicine(
    id: 'm56',
    name: 'Fluconazole (Chống nấm)',
    usage: 'Điều trị nhiễm nấm âm đạo, miệng, thực quản, hệ thống.',
    dosage: '150mg liều đơn (nấm âm đạo) hoặc 100-400mg/ngày tùy nhiễm trùng.',
    warning: 'Có thể gây tăng men gan. Tương tác nhiều với thuốc khác. Kiểm tra chức năng gan khi dùng lâu.',
  ),
  Medicine(
    id: 'm57',
    name: 'Ketoconazole (Chống nấm)',
    usage: 'Điều trị nhiễm nấm da, móng, toàn thân.',
    dosage: '200-400mg/ngày.',
    warning: 'Có thể gây độc gan nghiêm trọng. Kiểm tra men gan thường xuyên. Uống với thức ăn chua.',
  ),
  Medicine(
    id: 'm58',
    name: 'Acyclovir (Chống virus)',
    usage: 'Điều trị herpes simplex, herpes zoster (zona), thủy đậu.',
    dosage: '200-800mg/lần, ngày 5 lần tùy bệnh.',
    warning: 'Hiệu quả tốt nhất khi dùng sớm (trong 24-48 giờ đầu). Uống nhiều nước. Có thể gây buồn nôn.',
  ),
  Medicine(
    id: 'm59',
    name: 'Oseltamivir (Tamiflu - Chống cúm)',
    usage: 'Điều trị và phòng ngừa cúm A, cúm B.',
    dosage: 'Điều trị: 75mg x 2 lần/ngày trong 5 ngày. Phòng ngừa: 75mg/ngày.',
    warning: 'Hiệu quả khi dùng trong 48 giờ đầu có triệu chứng. Có thể gây buồn nôn, nói. Không thay thế vắc xin cúm.',
  ),
  Medicine(
    id: 'm60',
    name: 'Lithium (Điều trị loạn thần)',
    usage: 'Điều trị rối loạn lưỡng cực, phòng ngừa tái phát hưng cảm và trầm cảm.',
    dosage: '300-1200mg/ngày chia nhiều lần, tùy nồng độ máu.',
    warning: 'Cần theo dõi nồng độ lithium máu thường xuyên. Có thể gây độc thận, giáp. Uống nhiều nước. Tránh giảm muối đột ngột.',
  ),
  Medicine(
    id: 'm61',
    name: 'Sertraline (Chống trầm cảm)',
    usage: 'Điều trị trầm cảm, rối loạn lo âu, OCD, PTSD.',
    dosage: '50-200mg/ngày, uống buổi sáng hoặc tối.',
    warning: 'Hiệu quả sau 2-4 tuần. Không ngừng đột ngột. Có thể gây buồn nôn, rối loạn tình dục, tăng cân.',
  ),
  Medicine(
    id: 'm62',
    name: 'Escitalopram (Chống trầm cảm)',
    usage: 'Điều trị trầm cảm và rối loạn lo âu.',
    dosage: '10-20mg/ngày.',
    warning: 'Thuốc nhóm SSRI. Hiệu quả sau vài tuần. Có thể gây buồn nôn ban đầu. Không uống rượu.',
  ),
  Medicine(
    id: 'm63',
    name: 'Duloxetine (Chống trầm cảm)',
    usage: 'Điều trị trầm cảm, lo âu, đau thần kinh do tiểu đường, đau cơ xương khớp mạn.',
    dosage: '30-60mg/ngày.',
    warning: 'Có thể gây buồn nôn, khô miệng, chóng mặt. Không ngừng đột ngột. Kiểm tra huyết áp.',
  ),
  Medicine(
    id: 'm64',
    name: 'Quetiapine (Chống loạn thần)',
    usage: 'Điều trị tâm thần phân liệt, rối loạn lưỡng cực, trầm cảm nặng.',
    dosage: '50-800mg/ngày chia 2 lần, tăng dần.',
    warning: 'Có thể gây buồn ngủ nặng, tăng cân, tăng đường huyết. Theo dõi cân nặng, đường huyết.',
  ),
  Medicine(
    id: 'm65',
    name: 'Risperidone (Chống loạn thần)',
    usage: 'Điều trị tâm thần phân liệt, kích động ở bệnh nhân Alzheimer.',
    dosage: '1-6mg/ngày chia 1-2 lần.',
    warning: 'Có thể gây rối loạn vận động, tăng prolactin, tăng cân. Người cao tuổi có nguy cơ đột quỵ cao hơn.',
  ),
];

final List<VideoItem> sampleVideos = [
  VideoItem(
    id: 'v1',
    title: 'Bài tập thể dục cho người cao tuổi',
    duration: '15:30',
    author: 'HTVC Gia Đình',
    thumbnailUrl: 'https://img.youtube.com/vi/L0gSC0vF3-Q/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=L0gSC0vF3-Q',
  ),
  VideoItem(
    id: 'v2',
    title: 'Nhạc thiền thư giãn dễ ngủ',
    duration: '60:00',
    author: 'Thiền Đạo',
    thumbnailUrl: 'https://img.youtube.com/vi/5qap5aO4i9A/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=5qap5aO4i9A',
  ),
  VideoItem(
    id: 'v3',
    title: 'Chăm sóc người cao tuổi tại nhà',
    duration: '12:45',
    author: 'BS. Gia Đình',
    thumbnailUrl: 'https://img.youtube.com/vi/6VZKRAr90Sw/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=6VZKRAr90Sw',
  ),
  VideoItem(
    id: 'v4',
    title: 'Yoga cho người cao tuổi buổi sáng',
    duration: '20:15',
    author: 'Yoga Instructor',
    thumbnailUrl: 'https://img.youtube.com/vi/8sRcpnTCqWs/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=8sRcpnTCqWs',
  ),
  VideoItem(
    id: 'v5',
    title: 'Bài tập dưỡng sinh buổi sáng',
    duration: '15:30',
    author: 'Sức Khỏe 365',
    thumbnailUrl: 'https://img.youtube.com/vi/T-QL6H-zDh4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=T-QL6H-zDh4',
  ),
  VideoItem(
    id: 'v6',
    title: 'Thể dục dưỡng sinh 18 động tác',
    duration: '25:00',
    author: 'Sức Khỏe Vàng',
    thumbnailUrl: 'https://img.youtube.com/vi/GjqVNj9pHC4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=GjqVNj9pHC4',
  ),
  VideoItem(
    id: 'v7',
    title: 'Bài tập giảm đau vai gáy',
    duration: '10:20',
    author: 'Vật Lý Trị Liệu',
    thumbnailUrl: 'https://img.youtube.com/vi/eU2-KXtqjzQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=eU2-KXtqjzQ',
  ),
  VideoItem(
    id: 'v8',
    title: 'Massage chân giúp ngủ ngon',
    duration: '08:30',
    author: 'Y Học Cổ Truyền',
    thumbnailUrl: 'https://img.youtube.com/vi/bLYfcClBhKo/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=bLYfcClBhKo',
  ),
  VideoItem(
    id: 'v9',
    title: 'Khí công dưỡng sinh',
    duration: '18:00',
    author: 'Khí Công Việt Nam',
    thumbnailUrl: 'https://img.youtube.com/vi/eXSKaLGw3kY/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=eXSKaLGw3kY',
  ),
  VideoItem(
    id: 'v10',
    title: 'Bài tập căng cơ toàn thân',
    duration: '12:45',
    author: 'Fitness Channel',
    thumbnailUrl: 'https://img.youtube.com/vi/sTANio_2E0Q/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=sTANio_2E0Q',
  ),
  VideoItem(
    id: 'v11',
    title: 'Thiền định buổi sáng',
    duration: '30:00',
    author: 'Thiền Nhạc',
    thumbnailUrl: 'https://img.youtube.com/vi/ssss7V1_eyA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=ssss7V1_eyA',
  ),
  VideoItem(
    id: 'v12',
    title: 'Bài tập thở sâu giảm stress',
    duration: '10:00',
    author: 'Yoga & Wellness',
    thumbnailUrl: 'https://img.youtube.com/vi/tybOi4hjZFQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=tybOi4hjZFQ',
  ),
  VideoItem(
    id: 'v13',
    title: 'Thể dục điều dưỡng cho người cao tuổi',
    duration: '15:00',
    author: 'VTV Sức Khỏe',
    thumbnailUrl: 'https://img.youtube.com/vi/L_0fZfL7bD8/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=L_0fZfL7bD8',
  ),
  VideoItem(
    id: 'v14',
    title: 'Bài tập chống loãng xương',
    duration: '12:30',
    author: 'Sức Khỏe Đời Sống',
    thumbnailUrl: 'https://img.youtube.com/vi/4BpOLvjRcXU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=4BpOLvjRcXU',
  ),
  VideoItem(
    id: 'v15',
    title: 'Bài tập cho người đau khớp gối',
    duration: '10:45',
    author: 'PT Chuyên Nghiệp',
    thumbnailUrl: 'https://img.youtube.com/vi/tZG-C7WgOKk/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=tZG-C7WgOKk',
  ),
  VideoItem(
    id: 'v16',
    title: 'Nhạc thư giãn giúp ngủ ngon',
    duration: '180:00',
    author: 'Relaxing Music',
    thumbnailUrl: 'https://img.youtube.com/vi/lTRiuFIWV54/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=lTRiuFIWV54',
  ),
  VideoItem(
    id: 'v17',
    title: 'Bài tập tay cho người tai biến',
    duration: '14:20',
    author: 'Phục Hồi Chức Năng',
    thumbnailUrl: 'https://img.youtube.com/vi/CG-TqbqbeFY/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=CG-TqbqbeFY',
  ),
  VideoItem(
    id: 'v18',
    title: 'Bài tập giảm mỡ bụng tuổi trung niên',
    duration: '15:00',
    author: 'Fitness Over 50',
    thumbnailUrl: 'https://img.youtube.com/vi/gfSB5hG5oBs/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=gfSB5hG5oBs',
  ),
  VideoItem(
    id: 'v19',
    title: 'Bài tập cân bằng tránh ngã',
    duration: '08:30',
    author: 'Safety First',
    thumbnailUrl: 'https://img.youtube.com/vi/g_tea8ZNk5A/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=g_tea8ZNk5A',
  ),
  VideoItem(
    id: 'v20',
    title: 'Yoga trên ghế cho người cao tuổi',
    duration: '20:00',
    author: 'Chair Yoga',
    thumbnailUrl: 'https://img.youtube.com/vi/U2JLekYSx78/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=U2JLekYSx78',
  ),
  VideoItem(
    id: 'v21',
    title: 'Bài tập ngồi văn phòng',
    duration: '10:00',
    author: 'Office Wellness',
    thumbnailUrl: 'https://img.youtube.com/vi/RqcOCBb4arc/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=RqcOCBb4arc',
  ),
  VideoItem(
    id: 'v22',
    title: 'Bài tập kéo giãn cơ toàn thân',
    duration: '15:00',
    author: 'Stretching Pro',
    thumbnailUrl: 'https://img.youtube.com/vi/g_BYB5fisWA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=g_BYB5fisWA',
  ),
  VideoItem(
    id: 'v23',
    title: 'Bài tập Pilates nhẹ nhàng',
    duration: '25:00',
    author: 'Pilates Anytime',
    thumbnailUrl: 'https://img.youtube.com/vi/OqZLUfD8eEE/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=OqZLUfD8eEE',
  ),
  VideoItem(
    id: 'v24',
    title: 'Bài tập giảm stress công việc',
    duration: '08:00',
    author: 'Stress Relief',
    thumbnailUrl: 'https://img.youtube.com/vi/inpok4MKVLM/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=inpok4MKVLM',
  ),
  VideoItem(
    id: 'v25',
    title: 'Bài tập sức bền cơ bắp',
    duration: '20:00',
    author: 'Senior Fitness',
    thumbnailUrl: 'https://img.youtube.com/vi/YTjMN52sRo4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=YTjMN52sRo4',
  ),
  VideoItem(
    id: 'v26',
    title: 'Bài tập cho người bệnh tim',
    duration: '12:00',
    author: 'Heart Health',
    thumbnailUrl: 'https://img.youtube.com/vi/YFZj6EP0_5c/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=YFZj6EP0_5c',
  ),
  VideoItem(
    id: 'v27',
    title: 'Bài tập thăng bằng và phối hợp',
    duration: '15:30',
    author: 'Balance Training',
    thumbnailUrl: 'https://img.youtube.com/vi/9HDFIYolo2o/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=9HDFIYolo2o',
  ),
  VideoItem(
    id: 'v28',
    title: 'Bài tập đi bộ trong nhà',
    duration: '30:00',
    author: 'Walking Workout',
    thumbnailUrl: 'https://img.youtube.com/vi/Sg4rc8tvSRw/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Sg4rc8tvSRw',
  ),
  VideoItem(
    id: 'v29',
    title: 'Bài tập aerobic nhẹ',
    duration: '20:00',
    author: 'Low Impact Aerobics',
    thumbnailUrl: 'https://img.youtube.com/vi/8P0iwMU_ZtE/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=8P0iwMU_ZtE',
  ),
  VideoItem(
    id: 'v30',
    title: 'Bài tập thư giãn buổi tối',
    duration: '15:00',
    author: 'Evening Relaxation',
    thumbnailUrl: 'https://img.youtube.com/vi/4pKly2JojMw/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=4pKly2JojMw',
  ),
];